### ISSUE TITLE
remove unmaintained tracker code

### ISSUE THREAD

**Issue by timroster** [IBM/BluePic#436]
The metrics tracker project is no longer maintained.

Remove the following:

- [ ]   Badge at top of README
- [ ]   Privacy Notice from Readme
- [ ]   Disabling Deployment Tracking from Readme
- [ ]   Use of metric tracker in app, i.e. require('metrics-tracker-client').track();
- [ ]   The metrics-tracker library from requirement.txt or package.json
- [ ]   The repository.yml file at the app level
